### ISSUE TITLE
CloudFormation or CDK stacks implementing this 

### ISSUE THREAD

**Issue by jkarvanen** [mike-calder/AIM368-Instructions#2]
Question: 
Is there any CloudFormation or CDK stacks implementing the same which is here implemented manually with console?
Or is there any other ready similar stacks?

**Comment by mike-calder** [comment]
Hi Jukka, at this time we don't have a pre-made CFN/CDK template that generates the resources created in this lab. With that said, it probably wouldn't be to difficult to make considering they are relatively common constructs. When we update/refresh the content this year I'll make a note to accompany it with CFN/CDK because I agree that would be helpful. Thanks!
